export let treeData = [
  {
    children: [
      {
        id: 11,
        isShow: 1,
        name: "曝光统计",
        parentId: 1,
        reportType: 1,
        themeIndex: 1,
        title: "11",
        templateStructureKey: "KaReport_CompetitorConsultCountDual",
      },
      {
        id: 12,
        isShow: 1,
        name: "曝光统计2",
        parentId: 1,
        reportType: 1,
        themeIndex: 1,
        title: "12",
        templateStructureKey: "KaReport_CompetitorConsultCountDual",
      },
      {
        id: 13,
        isShow: 0,
        name: "曝光统计add",
        parentId: 1,
        reportType: 1,
        themeIndex: 1,
        title: "13",
        templateStructureKey: "KaReport_CompetitorConsultCountDual",
      },
      {
        "id": 14,
        "isShow": 0,
        "name": "曝光统计add",
        "parentId": 1,
        "reportType": 1,
        "themeIndex": 1,
        "title": "14",
        "templateStructureKey": "KaReport_CompetitorConsultCountDual"
      },
    ],
    id: 1,
    isShow: 1,
    name: "一级主题1",
    parentId: 0,
    reportType: 1,
    templateStructureKey: "",
    themeIndex: 1,
    title: "1",
  },
  {
    children: [
      {
        id: 21,
        isShow: 1,
        name: "门店拜访",
        parentId: 2,
        reportType: 1,
        themeIndex: 1,
        title: "21",
        templateStructureKey: "KaReport_CompetitorConsultCountDual",
      },
      {
        id: 22,
        isShow: 1,
        name: "门店拜访2",
        parentId: 2,
        reportType: 1,
        themeIndex: 1,
        title: "22",
        templateStructureKey: "KaReport_CompetitorConsultCountDual",
      },
      {
        id: 23,
        isShow: 1,
        name: "门店拜访23",
        parentId: 2,
        reportType: 1,
        themeIndex: 1,
        title: "23",
        templateStructureKey: "KaReport_CompetitorConsultCountDual",
      },
    ],
    id: 2,
    isShow: 0,
    name: "一级主题1",
    parentId: 0,
    reportType: 1,
    templateStructureKey: "",
    themeIndex: 2,
    title: "2",
  },
];